language: node_js
node_js:
  - "0.11"
  - "0.10"
  - "0.8"
branches:
  only:
    - webdriver
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - bin/hardy selenium start
  - sleep 10
  - firefox --version
  - phantomjs --version
